name: 'myapp'
services:
  webapp:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - postgres
    environment:
      MODE: ${MODE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SQS_URL: ${SQS_URL}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8084:8084"

  postgres:
    image: 'postgres:17'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "25432:5432"
